### ISSUE TITLE
Hey, this is used by Sims Online?

### ISSUE THREAD

**Issue by francot514** [daddesio/utkencode#3]
Hey how you doing this is used by The Sims online, and instructions to use it.

**Comment by daddesio** [comment]
Hi franco!

In The Sims Online, all the UTK files are stored in tsov2.dat, which is an uncompressed DBPF archive, which you can extract using farextract.

You can convert UTK to WAV using utkdecode or vgmstream.

utkencode is meant for converting WAV to UTK. Originally, I planned on adding a psychoacoustic model to utkencode to make it higher quality than EA's Sound Exchange tool (sx.exe), but Sound Exchange already gives very good quality speech, so I never got around to it.
